src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]

class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    #[ORM\Column]
    private ?int $progress_percent = null;


    #[ORM\ManyToOne(inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Project $associated_project = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'tasks')]
    private Collection $associated_user;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    public function __construct()
    {
        $this->associated_user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getProgressPercent(): ?int
    {
        return $this->progress_percent;
    }

    public function setProgressPercent(int $progress_percent): static
    {
        $this->progress_percent = $progress_percent;

        return $this;
    }

    public function getAssociatedProject(): ?project
    {
        return $this->associated_project;
    }

    public function setAssociatedProject(?project $associated_project): static
    {
        $this->associated_project = $associated_project;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getAssociatedUser(): Collection
    {
        return $this->associated_user;
    }

    public function addAssociatedUser(User $associatedUser): static
    {
        if (!$this->associated_user->contains($associatedUser)) {
            $this->associated_user->add($associatedUser);
        }

        return $this;
    }

    public function removeAssociatedUser(User $associatedUser): static
    {
        $this->associated_user->removeElement($associatedUser);

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }


    public function updateProgressPercentage(): void
    {
        // Exemple de logique : pending = 50, completed = 100, sinon 0 (ou une autre valeur par défaut)
        if ($this->state === 'in_progress') {
            $this->progress_percent = 50;
        } elseif ($this->state === 'completed') {
            $this->progress_percent = 100;
        } else {
            $this->progress_percent = 0;
        }
        
    }
}

src/Form/TaskType.php
<?php
// src/Form/TaskType.php

namespace App\Form;

use App\Entity\Task;
use App\Entity\User;
use App\Entity\Project;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Récupération de l'utilisateur connecté passé en option
        $currentUser = $options['current_user'];
       
      
      
        
        $builder
            ->add('name')
            ->add('state', ChoiceType::class, [
                'choices'  => [
                    'Pending'     => 'pending',
                    'In Progress' => 'in_progress',
                    'Completed'   => 'completed',
                ],
            ])
            // Champ caché pour progress_percent, non mappé pour ignorer toute saisie utilisateur
            ->add('progress_percent', HiddenType::class, [
                'mapped' => false,
            ])
            ->add('start_date', null, [
                'widget' => 'single_text',
            ])
            ->add('end_date', null, [
                'widget' => 'single_text',
            ])
            ->add('associated_project', EntityType::class, [
                'class' => Project::class,
                // On utilise la propriété "name" pour afficher le nom du projet
                'choice_label' => 'name',
            ])
            ->add('associated_user', EntityType::class, [
                'class' => User::class,
                // On affiche l'email de l'utilisateur
                'choice_label' => 'email',
                'multiple' => true,
                'placeholder' => 'Sélectionnez un utilisateur',
                // Utilisation du currentUser pour filtrer les utilisateurs par projets
                'query_builder' => function (EntityRepository $er) use ($currentUser) {
                    $projectIds = array_map(function($project) {
                        return $project->getId();
                    }, $currentUser->getProjects()->toArray());
                    
                    return $er->createQueryBuilder('u')
                        ->innerJoin('u.projects', 'p')
                        ->where('p.id IN (:projectIds)')
                        ->setParameter('projectIds', $projectIds);
                },
            ])
        ;

        // Ajout d'un event listener pour mettre à jour progress_percent en fonction de l'état de la tâche
        $builder->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $event) {
            /** @var Task $task */
            $task = $event->getData();
            switch ($task->getState()) {
                case 'pending':
                    $task->setProgressPercent(0);
                    break;
                case 'in_progress':
                    $task->setProgressPercent(50);
                    break;
                case 'completed':
                    $task->setProgressPercent(100);
                    break;
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'   => Task::class,
            // Ajout de l'option current_user sans supprimer les autres options
            'current_user' => null,
        ]);

        // Définir le type autorisé pour current_user
        $resolver->setAllowedTypes('current_user', ['null', User::class]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\ProjectRepository;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/task')]
final class TaskController extends AbstractController
{
    #[Route(name: 'app_task_index', methods: ['GET'])]
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('task/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }

    #[Route("/project/{id}", name: 'app_task_project', methods: ['GET','POST'])]
    public function taskByProjects(Request $request, ProjectRepository $projectRepository,TaskRepository $taskRepository): Response
    {
        $id = $request->attributes->get('id');

        // Récupération du projet et des tâches correspondantes
        $project = $projectRepository->find($id);
        $tasks = $taskRepository->findBy([
            "associated_project" => $id
        ]);

        // Création d'une nouvelle tâche par exemple
        $task = new Task();

        // Passage de l'utilisateur connecté dans le formulaire
        $form = $this->createForm(TaskType::class, $task, [
            'current_user' => $this->getUser(),
        ]);

        return $this->render('task/index.html.twig', [
            'tasks' => $tasks,
            'project' => $project,
            'id' => $id,
            'form' => $form->createView(),
        ]);
    }

    #[Route("/project/state/{idProject}/{id}/{state}", name: 'app_task_project_state', methods: ['GET'])]
    public function stateBytaskProject(EntityManagerInterface $entityManager, TaskRepository $taskRepository, Request $request): Response
    {

        $state = $request->attributes->get('state');
        $id = $request->attributes->get('id');
        $idProject = $request->attributes->get('idProject');


        $task = $taskRepository->find($id);

        $task->setState($state);
        $task->updateProgressPercentage();

        $entityManager->flush();


        return $this->redirectToRoute('app_task_project', ['id' => $idProject], Response::HTTP_SEE_OTHER);

        // return new Response(null, Response::HTTP_NO_CONTENT);
    }


    #[Route('/new/{id}', name: 'app_task_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $task = new Task();
        $id = $request->attributes->get("id");
        // Dans votre contrôleur
    
        $form = $this->createForm(TaskType::class, $task, [
            'current_user' => $this->getUser(),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('app_task_project', ['id' => $id,'user' => $this->getUser()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/new.html.twig', [
            'id' => $id,
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_task_show', methods: ['GET'])]
    public function show(Task $task): Response
    {
        $project = $task->getAssociatedProject();

        return $this->render('task/show.html.twig', [
            'task' => $task,
            'project' => $project,
        ]);
    }


    #[Route('/{id}/edit', name: 'app_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        // Dans votre contrôleur
        $form = $this->createForm(TaskType::class, $task, [
            'current_user' => $this->getUser(), // ou la méthode adaptée pour récupérer l'utilisateur connecté
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{idProject}/{id}', name: 'app_task_delete', methods: ['POST'])]
    public function delete(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        $idProject=$request->attributes->get('idProject');
        if ($this->isCsrfTokenValid('delete' . $task->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_task_project', ['id'=>$idProject], Response::HTTP_SEE_OTHER);
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_task_index') }}">back to list</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index
{% endblock %}

{% block body %}


	<div class="container mx-auto px-4 sm:px-8">
		<div class="py-8">
			<h1 class="text-3xl font-bold mb-6">Task of Project {{project.name}} </h1>
			<div class="overflow-x-auto">
				<table class="min-w-full leading-normal shadow rounded-lg overflow-hidden">
					<thead>
						<tr>
							<th class="px-5 py-3 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Id</th>
							<th class="px-5 py-3 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Name</th>
							<th class="px-5 py-3 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">State</th>
							<th class="px-5 py-3 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Progress Percent</th>
							<th class="px-5 py-3 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Start Date</th>
							<th class="px-5 py-3 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">End Date</th>
							<th class="px-5 py-3 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for task in tasks %}
							<tr class="bg-white hover:bg-gray-50">
								<td class="px-5 py-5 border-b border-gray-200 text-sm">{{ task.id }}</td>
								<td class="px-5 py-5 border-b border-gray-200 text-sm">{{ task.name }}</td>
								<td class="px-5 py-5 border-b border-gray-200 text-sm">
									<select class="block w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring focus:border-indigo-500" onchange="if(this.value) { window.location.href = this.value; }">
										<option value="{{ path('app_task_project_state', {'idProject': id,'id': task.id, 'state': 'pending'}) }}" {% if task.state == 'pending' %} selected {% endif %}>
											A faire
										</option>
										<option value="{{ path('app_task_project_state', {'idProject': id,'id': task.id, 'state': 'in_progress'}) }}" {% if task.state == 'in_progress' %} selected {% endif %}>
											En cours
										</option>

										{# {{ path('app_task_project_state', {'id': task.id, 'state': 'completed'}) }} #}
										<option value="{{ path('app_task_project_state', {'idProject': id,'id': task.id, 'state': 'completed'}) }}" {% if task.state == 'completed' %} selected {% endif %}>
											Terminée
										</option>
									</select>
								</td>
								<td class="px-5 py-5 border-b border-gray-200 text-sm">
									<div class="w-full bg-gray-200 rounded-full h-4">
										<div class="bg-indigo-500 h-4 rounded-full" style="width: {{ task.progressPercent }}%;"></div>
									</div>
									<div class="mt-1 text-xs font-medium text-gray-600 text-right">
										{{ task.progressPercent }}%
									</div>
								</td>
								<td class="px-5 py-5 border-b border-gray-200 text-sm">
									{{ task.startDate ? task.startDate|date('Y-m-d H:i:s') : '' }}
								</td>
								<td class="px-5 py-5 border-b border-gray-200 text-sm">
									{{ task.endDate ? task.endDate|date('Y-m-d H:i:s') : '' }}
								</td>
								<td class="px-5 py-5 border-b border-gray-200 text-sm text-center">
									<a href="{{ path('app_task_show', {'id': task.id}) }}" class="text-indigo-600 hover:text-indigo-900 mr-2">Show</a>
									{# <a href="{{ path('app_task_edit', {'id': task.id}) }}" class="text-indigo-600 hover:text-indigo-900 mr-2">Edit</a> #}
									<form action="{{ path('app_task_delete', {'id': task.id, 'idProject': project.id}) }}" method="post" style="display:inline;">
										<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
										<button type="submit" class="text-red-600 hover:text-red-900">Delete</button>
									</form>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="7" class="px-5 py-5 border-b border-gray-200 text-sm text-center">No records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="mt-6">
				<a href="{{ path('app_task_new',  {'id': id}) }}" class="bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded mr-2">
					Create new
				</a>

				<!-- Project List Button -->
				<a href="{{ path('app_project_index') }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mr-2">
					Project List
				</a>

				<!-- Logout Button -->
				<a href="{{ path('app_logout') }}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
					Logout
				</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire TaskType{% endblock %}

{% block body %}
<div class="min-h-screen flex items-center justify-center ">
  <div class="w-full max-w-lg bg-white p-8 rounded shadow">
    <h1 class="text-2xl font-bold mb-6 text-center">Formulaire TaskType</h1>
    {{ form_start(form, {'attr': {'class': 'space-y-6'}}) }}

    {% for child in form %}
      {% if child.vars.name != 'ss' %}
        <div>
          {{ form_label(child, null, {'label_attr': {'class': 'block text-gray-700'}}) }}
          {{ form_widget(child, {'attr': {'class': 'mt-1 block w-full border border-gray-300 rounded-md p-2 focus:outline-none focus:ring focus:border-indigo-500'}}) }}
          {{ form_errors(child) }}
        </div>
   {% endif %}
    {% endfor %}

    <div class="text-right">
      <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded hover:bg-indigo-700 transition duration-200">
        Enregistrer
      </button>
    </div>

    {{ form_end(form) }}
  </div>
</div>

    <script>
        // Si le hash "#reloaded" n'est pas présent dans l'URL, on le rajoute et on recharge la page.
        if (!window.location.hash) {
            window.location.href = window.location.href + "#reloaded";
            window.location.reload();
        }
    </script>
{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task Details
{% endblock %}

{% block body %}
	<div class="max-w-3xl mx-auto p-6  bg-white  shadow-lg rounded-lg">
		<h1 class="text-2xl font-bold text-gray-800 mb-4">Task Details</h1>

		<table class="w-full border-collapse border border-gray-300 rounded-lg">
			<tbody class="divide-y divide-gray-200">
				<tr>
					<th class="p-2 text-left bg-gray-100">Id</th>
					<td class="p-2">{{ task.id }}</td>
				</tr>
				<tr>
					<th class="p-2 text-left bg-gray-100">Name</th>
					<td class="p-2">{{ task.name }}</td>
				</tr>
				<tr>
					<th class="p-2 text-left bg-gray-100">State</th>
					<td class="p-2">{{ task.state }}</td>
				</tr>
				<tr>
					<th class="p-2 text-left bg-gray-100">Progress</th>
					<td class="p-2">{{ task.progressPercent }}%</td>
				</tr>
				<tr>
					<th class="p-2 text-left bg-gray-100">Start Date</th>
					<td class="p-2">{{ task.startDate ? task.startDate|date('Y-m-d H:i:s') : 'N/A' }}</td>
				</tr>
				<tr>
					<th class="p-2 text-left bg-gray-100">End Date</th>
					<td class="p-2">{{ task.endDate ? task.endDate|date('Y-m-d H:i:s') : 'N/A' }}</td>
				</tr>
				<tr>
					<th class="p-2 text-left bg-gray-100">Associated Project</th>
					<td class="p-2">
						{% if task.getAssociatedProject() %}
							<a href="{{ path('app_project_show', {'id': task.getAssociatedProject().id}) }}" class="text-blue-500 hover:underline">
								View Project:
								{{ task.getAssociatedProject().name }}
							</a>
						{% else %}
							No project associated
						{% endif %}
					</td>
				</tr>
			</tbody>
		</table>

		<div class="mt-4 flex space-x-4">
			<a href="{{ path('app_task_project',{'id':project.id}) }}" class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700">Back to Task List</a>
			{# <a href="{{ path('app_task_edit', {'id': task.id}) }}" class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">Edit</a> #}
		</div>

		{# <div class="mt-4">
			<form action="{{ path('app_task_delete', {'id': task.id }) }}" method="post" style="display:inline;">
				<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
				<button type="submit" class="text-red-600 hover:text-red-900">Delete</button>
			</form>
		</div> #}
	</div>
{% endblock %}